version: "3.7"

services:
  dummy:
    image: alpine
    command: sleep 10000
    init: true
  mocker:
    build: .
    command: sh -c 'yarn tsc && node dist/entrypoint.js'
    ports:
      - 7090:80
    environment:
      - PORT=80
      - URL=https://swapi.graph.cool
      - MOCKS_PATH=/mocks.js
      - PRESERVE_MUTATIONS=1
      - PRESERVE_QUERIES=allAssets
    volumes:
      - ./tests/mocks.js:/mocks.js
      - ./src:/src/src

# examples

# mutation {
#   createStarship(name: "ccc") {
#     class
#   }
# }

# query {
#   allAssets {
#     fileName
#     createdAt
#   }
#   allFilms {
#     createdAt
#     director
#   }
# }


