version: "3"

services:
  mocker:
    build: .
    ports:
      - 7090:80
    environment:
      - PORT=80
      - URL=http://gqlapi:8080/graphql
      - MOCKS_PATH=/mocks.js
    volumes:
      - ./tests/mocks.js:/mocks.js
  gqlapi:
    ports:
      - 7060:8080
    image: rm3l/docker-api-graphql
    expose: [8080]
    environment:
      - API_ENDPOINT=/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
